name: "Nitpick AI"
description: "A GitHub Action that performs code review using AI."
author: "Alexander Taraymovich"
runs:
  using: "node20"
  main: "dist/index.js"

inputs:
  github-token:
    description: "GitHub token for posting reviews"
    required: true
  ai-model:
    description: "AI model to use for the review. Accepted values are: claude-3.5-sonnet (recommended) and gpt-3.5"
    required: true
    default: "claude-3.5-sonnet"
  api-key:
    description: "API key for the AI model"
    required: true
  strict:
    description: "Whether to request changes or post review as a comment"
    required: false
    default: "false"
  ignore-patterns:
    description: "Array of glob patterns for files to ignore"
    required: false
    default: "[]"

branding:
  icon: 'zap'
  color: 'purple'